### ISSUE TITLE
Adding to plugin marketplace.

### ISSUE THREAD

**Issue by sawhney17** [tobealive/logseq-allday-theme#1]
Would love for this to be added to the plugin marketplace. Will make it easier to discover and install the theme for new users and also allow for easy updates. I can submit a PR on your behalf if you'd like.

**Comment by tobealive** [comment]
Hello, nice to read your message. Thanks for the suggestion and info. OC feel free to submit the PR!

**Comment by sawhney17** [comment]
For it to be approved, this repo needs to have a legal package.json file and a license. Should i submit a PR here as well?

**Comment by tobealive** [comment]
Hello,

That would be awesome. I'm pretty busy currently so everyones input is welcome. Thanks alot to you!

**Comment by sawhney17** [comment]
I've submitted a PR to this repo, once it's merged, I'll check off the remaining tasks on the marketplace repo.

**Comment by sawhney17** [comment]
@tobealive It's now available in the marketplace!

**Comment by tobealive** [comment]
Thank you so much Brother for your help with making it available as early as possible! I hope the community likes it ♥.
