### ISSUE TITLE
Headings Under Queries should be was slightly hidden on the left

### ISSUE THREAD

**Issue by Sachin-12** [tobealive/logseq-allday-theme#14]
As you can see, the headings under queries can be moved right for better visibility. Thanks for this great theme. I guess this issue was there from the time I started using your theme since 2 months

Hardware: MacBook M1
OS: MacOS 12.3
Logseq Version: 0.8.2

 
<img width="1176" alt="Screenshot 2022-08-24 at 4 46 39 AM" src="https://user-images.githubusercontent.com/24960422/186282905-554de35b-b704-4a7e-b908-2a207ad2bda7.png">

**Comment by tobealive** [comment]
Hey @Sachin-12,

Thanks for reaching out! I'm looking into it this evening 🧐
