### ISSUE TITLE
Text on the sidebar became black after recent Logseq update

### ISSUE THREAD

**Issue by SDD701** [tobealive/logseq-allday-theme#16]
### Light theme
![image](https://user-images.githubusercontent.com/62739248/197993887-d730972a-434e-4c61-9844-627a3e7c3779.png)
### Dark theme
![image](https://user-images.githubusercontent.com/62739248/197994015-a1db97b2-ec19-434a-bfe5-7ceaf6d76e80.png)

**Comment by tobealive** [comment]
Hey @SDD701 thanks for report the problem. I'll check on it tomorrow and push the necessary fixes!
