### ISSUE TITLE
Hard to read checkboxes

### ISSUE THREAD

**Issue by amwnag** [tobealive/logseq-allday-theme#17]
Checkboxes only display properly when hovering over them

![image](https://user-images.githubusercontent.com/86573349/209204629-950b0193-fcc1-43a3-a8ae-7cd1151f12ca.png)

**Comment by tobealive** [comment]
Hey @amwnag,

Thanks for reporting this issue. 
Will be completed tomorrow 🙂👍

**Comment by tobealive** [comment]
There has been a security issue that has taken up the whole day at work, so I am quite late getting to work on this.

I am having trouble reproducing the problem. Can you provide more information on:
1. operating system
2. logseq version
3. the context in which the problem occurs (at first glance it looks like it's in plugin settings, but checking the boxes for e.g., Logseqs Vim plugin, they look fine)


Translated with www.DeepL.com/Translator (free version)

**Comment by amwnag** [comment]
Got it. I'm using Windows 10 and Logseq version 0.8.14 (latest).

The problem occurs where checkboxes are present, so both settings and documents. Initially when marking the box as completed, it does appear as the correct color. After clicking away from the block, the blue color is gone, even if I were to select the box again.

![image](https://user-images.githubusercontent.com/86573349/209410474-b62735e4-e97f-45a3-8120-8decd7c67117.png)
