### ISSUE TITLE
[Error]<logseq-allday-theme> :release-channel-issue "Github API Failed(404) {\"message\":\"Not Found\",\"documentation_url\":\"https://docs.github.com/rest/reference/repos#get-the-latest-release\"}"]

### ISSUE THREAD

**Issue by e-buttelli** [tobealive/logseq-allday-theme#19]
Cannot install on version 0.9.2

**Comment by necropolina** [comment]
Looks like a release needs to be made.

**Comment by tobealive** [comment]
Sorry for not having investigated this further. I'm looking into it this evening. Thanks for the hint!

**Comment by tobealive** [comment]
Can you please confirm if the issue is solved for you?
