### ISSUE TITLE
todo boxes

### ISSUE THREAD

**Issue by manox-myth** [tobealive/logseq-allday-theme#7]
The frame of boxes in dark mode are not visible.

**Comment by tobealive** [comment]
Hey, thanks for reaching out 🚀

Can you post a screenshot that I can tackle exaclty what you mean?

Best regards

**Comment by manox-myth** [comment]
![Screenshot_20220413-133753_Logseq.jpg](https://user-images.githubusercontent.com/97319687/163172033-1664ba25-55d2-46fb-be9b-848bd3eb111c.jpg)

**Comment by tobealive** [comment]
Thanks for the screenshot brother.

And yes, this is not the way it should be. I’ll check on this tomorrow. It has ben a pretty long working session, over the last two days.

**Comment by manox-myth** [comment]
No problem, I'm using the white theme now. : )

**Comment by tobealive** [comment]
Hey, hello :), please forgive the late reply. 

It's that I can't reproduce the problem. Checked this on two Systems, and the boxes are visible on all the background colors the theme is using.

Here a screenshot from my potato computer:
![boxes](https://user-images.githubusercontent.com/34311583/163624997-8f057a2b-dac4-4540-872b-d2f318da9c48.jpg)



Probably logseq has something in it's cache from another theme. You tried clearing it?

**Comment by manox-myth** [comment]
Hello, no problem. Yes, I tried. Maybe it's a phone specific problem. I also tried both nightly and stable Logseq versions. Boxes are not visible for me. I don't have other things in custom.css just your theme. I don't know what the problem is. 😱

**Comment by tobealive** [comment]
Ahh, now I understand that it's about the mobile version which I didnt checked.

This brings us closer to solving it. I'm looking into it today.

**Comment by tobealive** [comment]
Please tell me which platform you are using, hopefully we can debug this 🤓.

**Comment by manox-myth** [comment]
Android 12, Samsung One UI4

**Comment by tobealive** [comment]
Testing it on Android it works normally for me.
![Screenshot_20220417_194417](https://user-images.githubusercontent.com/34311583/163726344-1a0f48e2-74be-4a49-975a-c0b96fa124d9.jpg)

I think there is not much I can do on my side unfortunately. 

Everything went right pasting the css?

**Comment by tobealive** [comment]
It's possible to reproduce it with the beta and nightly release. I'll check how this can be implemented without affecting the stable releases, which of course are prioritized.

**Comment by manox-myth** [comment]
It doesn't work on the current stable release either.

**Comment by tobealive** [comment]
v0.6.6 is a beta release.

Anyway, it's solved now 😊👍

**Comment by manox-myth** [comment]
@tobealive thanks a lot! you're awesome! I have a few questions, do you have Discord?

**Comment by tobealive** [comment]
Yes, I have it installed but didn't come to use it much till now. Should I add you?

**Comment by manox-myth** [comment]
> Yes, I have it installed but didn't come to use it much till now. Should I add you?

If you do not mind :) manox_myth#7888
