### ISSUE TITLE
[Bug] Advanced query title header not rendered correctly

### ISSUE THREAD

**Issue by piyush-das** [tobealive/logseq-allday-theme#8]
Hi,

If we mention a title in query as `title [:h2 "Attempted Questions"]`, then it does not render correctly 
![image](https://user-images.githubusercontent.com/68941107/173227673-5f80855b-fb7c-406d-a092-af4c68843801.png)

Thanks

**Comment by tobealive** [comment]
Hey thanks for reaching out! I'll check and update it 👍️

**Comment by tobealive** [comment]
Hey, I finally came to look into it. Sorry that it took a while.

Should work in the new version.
